name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Default permission for accessing the repository contents
      id-token: write # Add this permission to allow the deployment to work

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Update Node.js version to 18

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact # This is the artifact name
          path: ./dist # Path to your build files (replace with your actual build output path)

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          artifact_name: my-artifact # Ensure this matches the name used in the upload step
