name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Upload artifact (Vite output folder)
        uses: actions/upload-artifact@v3
        with:
          path: ./dist # Vite's output folder

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
