name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Ensure this matches the version you need

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Check build output
        run: |
          ls -la ./dist  # Ensure the output is in the dist folder

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact # The name of the artifact (must match the deploy step)
          path: ./dist # Path to your build files

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          artifact_name: my-artifact # Ensure this matches the name used in the upload step
